





 



<p class="comment">
**Practice S5:** Analysis of Co-variance: interpret the following interaction plot after looking at the corresponding linear model. Build your an anova table - reverse your independent variables `Petal.Length` and `Species` in another `lm`. Compare the two `lm` models for their F-values and level of significance. Explain.
</p>

```{r,  eval=T, warning=F, message=F, echo=F}
fitiris <- lm(Petal.Width ~ Petal.Length*Species, data = iris)
interact_plot(fitiris, pred = Petal.Length, modx = Species, plot.points=T)
```

```{r, code_folding = 'Show Solution',  eval=F}
fitiris <- lm(Petal.Width ~ Petal.Length*Species, data = iris)
# In evaluating an ANCOVA model, we want to sequentially ask first whether there is a difference in slope, then if there is not, look for differences in intercept. 
# In addition, there is variety of way to calculate the sum of squares. Here (but this debatable), we would prefer a type 3 Anova especially since we have an interaction term in our Ancova (see Homogeneity of slope assumption in ANCOVA)
car::Anova(fitiris, type = 3)
```






